shell:
  program: /usr/local/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

window:
  decorations: buttonless
  startup_mode: Fullscreen

# default font size upon startup
font:
  size: 25

# Base16 Tomorrow Night 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'
  # Normal colors
  normal:
    black:   '0x1d1f21'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xc5c8c6'
  # Bright colors
  bright:
    black:   '0x969896'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xffffff'

# Use `xxd -psd` to get hex dump of tmux commands
key_bindings:
  - { key: T, mods: Command, chars: "\x60\x63" }         # Command-T send chars `c in tmux (new window)
  - { key: H, mods: Command, chars: "\x60\x68" }         # Command-H send chars `h in tmux (go to left pane)
  - { key: J, mods: Command, chars: "\x60\x6a" }         # Command-J send chars `j in tmux (go to below pane)
  - { key: K, mods: Command, chars: "\x60\x6b" }         # Command-K send chars `k in tmux (go to above pane)
  - { key: L, mods: Command, chars: "\x60\x6c" }         # Command-L send chars `l in tmux (go to right pane)
  - { key: Tab, mods: Control, chars: "\x60\x6e" }       # Control-Tab send chars `n in tmux (next window)
  - { key: Tab, mods: Control|Shift, chars: "\x60\x70" } # Control-Shift-Tab send chars `p in tmux (previous window)
  - { key: Comma, mods: Command, chars: "\x60\x2c" }     # Command-Comma send chars `, in tmux (rename window)
