name: dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  install-mac:
    runs-on: macos-latest

    steps:
      - name: Install dotfiles
        env:
            TOKEN: ${{ secrets.GA_PAT_TOKEN }}
        run: curl -fsSL https://raw.githubusercontent.com/apeduru/dotfiles/4e0a498c9a757b7d57f8e397931d77bc96602178/install | bash
        shell: bash

