name: dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  install-mac:
    runs-on: macos-latest

    steps:
      - name: Install dotfiles
        run: curl -fsSL https://raw.githubusercontent.com/apeduru/dotfiles/master/install | bash
