name: dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}

      - name: Install dotfiles
        run: curl -fsSL https://raw.githubusercontent.com/apeduru/dotfiles/master/install | bash
