name: dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  install-mac:
    runs-on: macos-latest

    steps:
      - name: Adding Known Hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
          known_hosts: "placeholder"

      - name: Install dotfiles
        run: curl -fsSL https://raw.githubusercontent.com/apeduru/dotfiles/ae09c3122696dd48fa75cdab92160b8e88d4bc5e/install | bash
