name: dotfiles

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  install-mac:
    runs-on: macos-latest

    steps:
      - name: Install dotfiles
        env:
            TOKEN: ${{ secrets.GA_PAT_TOKEN }}
        run: curl -fsSL https://raw.githubusercontent.com/apeduru/dotfiles/f1e6cd5e2d71005ba8f21652bdc96e3c5e6ea0b6/install | bash
        shell: bash

